In [16]:
import pandas as pd
import numpy as np

### xgb

In [17]:
xgb = pd.read_csv('xgb.csv', header = None)

In [18]:
xgb

,0,1,2,3,4,5,6
0,train_n_100_lr_0.3_d_3_child_1,438.95,438.61,444.65,436.71,440.97,439.98
1,val_n_100_lr_0.3_d_3_child_1,465.61,472.75,447.77,478.95,456.21,464.26
2,train_n_100_lr_0.3_d_3_child_2,439.90,438.32,444.60,436.83,440.92,440.11
3,val_n_100_lr_0.3_d_3_child_2,464.40,472.18,448.26,479.38,454.27,463.70
4,train_n_100_lr_0.3_d_3_child_5,440.25,440.50,444.57,436.06,443.75,441.03
...,...,...,...,...,...,...,...
939,val_n_500_lr_0.05_d_6_child_30,467.18,472.51,449.40,477.47,456.22,464.56
940,train_n_500_lr_0.05_d_6_child_50,419.06,417.77,424.82,415.26,421.72,419.73
941,val_n_500_lr_0.05_d_6_child_50,466.09,474.33,448.72,480.41,455.03,464.92
942,train_n_500_lr_0.05_d_6_child_100,430.38,430.04,435.29,427.51,434.16,431.48
943,val_n_500_lr_0.05_d_6_child_100,465.95,476.02,450.00,481.78,456.31,466.01

In [19]:
val = xgb[1::2]
val_top20 = val.sort_values([6])[:20]
val_top20

,0,1,2,3,4,5,6
611,val_n_200_lr_0.1_d_4_child_16,462.56,468.17,445.83,476.63,453.64,461.37
691,val_n_500_lr_0.05_d_4_child_20,463.25,468.52,446.35,476.16,453.38,461.53
687,val_n_500_lr_0.05_d_4_child_12,462.97,468.56,446.60,476.03,453.75,461.58
613,val_n_200_lr_0.1_d_4_child_20,462.71,469.46,446.25,476.61,453.45,461.70
575,val_n_100_lr_0.1_d_6_child_16,462.30,468.50,446.04,477.23,454.51,461.72
653,val_n_200_lr_0.05_d_6_child_16,463.00,468.71,446.42,476.89,453.71,461.75
631,val_n_200_lr_0.1_d_5_child_20,465.10,468.69,445.74,475.70,453.56,461.76
689,val_n_500_lr_0.05_d_4_child_16,463.72,468.18,446.71,476.73,453.71,461.81
319,val_n_500_lr_0.05_d_4_child_10,463.07,468.39,446.92,477.10,453.62,461.82
743,val_n_1000_lr_0.05_d_3_child_16,462.73,468.85,447.08,476.81,453.70,461.83
635,val_n_200_lr_0.05_d_5_child_16,462.80,469.16,446.24,477.84,453.46,461.90
863,val_n_200_lr_0.1_d_4_child_50,463.51,469.24,446.63,477.35,453.12,461.97
223,val_n_200_lr_0.05_d_5_child_10,463.55,468.94,446.19,477.54,453.67,461.98
633,val_n_200_lr_0.05_d_5_child_12,463.50,468.98,445.51,477.75,454.15,461.98
555,val_n_100_lr_0.1_d_5_child_12,463.73,468.72,447.05,477.26,453.18,461.99
667,val_n_500_lr_0.1_d_3_child_20,463.71,469.91,447.18,475.37,453.86,462.01
917,val_n_500_lr_0.05_d_4_child_50,463.34,469.41,447.22,477.16,452.98,462.02
255,val_n_200_lr_0.05_d_6_child_10,463.37,468.67,447.05,477.32,453.93,462.07
609,val_n_200_lr_0.1_d_4_child_12,462.96,469.36,446.41,477.77,453.94,462.09
665,val_n_500_lr_0.1_d_3_child_16,463.22,469.61,446.99,477.08,453.85,462.15

In [20]:
train_top20 = xgb.iloc[[i-1 for i in val_top20.index]]
train_top20

,0,1,2,3,4,5,6
610,train_n_200_lr_0.1_d_4_child_16,435.60,436.14,440.45,433.09,439.29,436.91
690,train_n_500_lr_0.05_d_4_child_20,433.74,432.62,437.18,430.93,436.54,434.20
686,train_n_500_lr_0.05_d_4_child_12,431.06,429.48,434.31,427.44,433.39,431.14
612,train_n_200_lr_0.1_d_4_child_20,436.80,436.43,440.81,434.53,440.46,437.81
574,train_n_100_lr_0.1_d_6_child_16,426.74,425.32,431.34,424.71,432.89,428.20
652,train_n_200_lr_0.05_d_6_child_16,427.77,426.21,432.89,425.21,432.02,428.82
630,train_n_200_lr_0.1_d_5_child_20,423.14,423.89,427.35,420.14,427.41,424.39
688,train_n_500_lr_0.05_d_4_child_16,432.01,431.03,435.94,430.31,435.32,432.92
318,train_n_500_lr_0.05_d_4_child_10,429.50,429.30,434.55,426.90,432.35,430.52
742,train_n_1000_lr_0.05_d_3_child_16,436.85,434.59,440.70,433.05,438.38,436.71
634,train_n_200_lr_0.05_d_5_child_16,437.40,436.58,443.52,436.90,441.54,439.19
862,train_n_200_lr_0.1_d_4_child_50,442.62,442.69,446.34,439.95,446.38,443.60
222,train_n_200_lr_0.05_d_5_child_10,434.84,434.46,441.34,433.75,439.01,436.68
632,train_n_200_lr_0.05_d_5_child_12,436.53,434.67,442.24,434.11,439.95,437.50
554,train_n_100_lr_0.1_d_5_child_12,435.18,433.93,441.66,433.75,438.32,436.57
666,train_n_500_lr_0.1_d_3_child_20,435.45,434.24,439.68,431.91,438.18,435.89
916,train_n_500_lr_0.05_d_4_child_50,440.32,438.83,444.06,437.15,442.72,440.62
254,train_n_200_lr_0.05_d_6_child_10,422.13,422.78,430.85,420.10,427.00,424.57
608,train_n_200_lr_0.1_d_4_child_12,434.78,433.52,438.72,431.63,437.24,435.18
664,train_n_500_lr_0.1_d_3_child_16,436.04,433.92,439.12,431.99,437.33,435.68

#### xgb (n_500_lr_0.05_d_4_child_10) or (n_200_lr_0.05_d_5_child_10)
##### n 늘려볼 필요 있음 -> n을 늘일 필요는 없어 보임

### gbr

In [21]:
gbr = pd.read_csv('gbr.csv', header = None)

In [22]:
val = gbr[1::2]
val_top20 = val.sort_values([6])[:20]
val_top20

,0,1,2,3,4,5,6
1007,val_lr_0.05_n_500_d_4_s_16_leaf_16,462.97,468.44,447.14,476.50,454.02,461.81
1003,val_lr_0.05_n_500_d_4_s_8_leaf_16,462.97,468.44,447.14,476.50,454.02,461.81
1011,val_lr_0.05_n_500_d_4_s_30_leaf_16,462.97,468.44,447.14,476.50,454.02,461.81
867,val_lr_0.1_n_200_d_4_s_30_leaf_16,462.91,468.97,446.89,477.39,452.97,461.83
859,val_lr_0.1_n_200_d_4_s_8_leaf_16,462.91,468.97,446.89,477.39,452.97,461.83
863,val_lr_0.1_n_200_d_4_s_16_leaf_16,462.91,468.97,446.89,477.39,452.97,461.83
983,val_lr_0.05_n_200_d_5_s_16_leaf_16,462.49,468.76,446.93,477.13,453.99,461.86
979,val_lr_0.05_n_200_d_5_s_8_leaf_16,462.49,468.76,446.93,477.13,453.99,461.86
987,val_lr_0.05_n_200_d_5_s_30_leaf_16,462.49,468.76,446.93,477.13,453.99,461.86
563,val_lr_0.1_n_200_d_4_s_6_leaf_10,464.54,468.59,446.42,476.31,454.47,462.07
575,val_lr_0.1_n_200_d_4_s_10_leaf_10,464.54,468.59,446.42,476.31,454.47,462.07
569,val_lr_0.1_n_200_d_4_s_8_leaf_10,464.54,468.59,446.42,476.31,454.47,462.07
573,val_lr_0.1_n_200_d_4_s_10_leaf_8,463.70,469.89,445.84,477.12,454.30,462.17
567,val_lr_0.1_n_200_d_4_s_8_leaf_8,463.70,469.89,445.84,477.12,454.30,462.17
561,val_lr_0.1_n_200_d_4_s_6_leaf_8,463.70,469.89,445.84,477.12,454.30,462.17
743,val_lr_0.05_n_200_d_5_s_6_leaf_10,463.62,469.43,446.29,477.63,453.94,462.18
749,val_lr_0.05_n_200_d_5_s_8_leaf_10,463.62,469.43,446.29,477.63,453.94,462.18
883,val_lr_0.1_n_500_d_3_s_8_leaf_16,463.53,469.65,446.98,477.06,453.68,462.18
887,val_lr_0.1_n_500_d_3_s_16_leaf_16,463.53,469.65,446.98,477.06,453.68,462.18
891,val_lr_0.1_n_500_d_3_s_30_leaf_16,463.53,469.65,446.98,477.06,453.68,462.18

In [23]:
train_top20 = gbr.iloc[[i-1 for i in val_top20.index]]
train_top20

,0,1,2,3,4,5,6
1006,train_lr_0.05_n_500_d_4_s_16_leaf_16,431.92,431.01,435.51,429.67,434.93,432.61
1002,train_lr_0.05_n_500_d_4_s_8_leaf_16,431.92,431.01,435.51,429.67,434.93,432.61
1010,train_lr_0.05_n_500_d_4_s_30_leaf_16,431.92,431.01,435.51,429.67,434.93,432.61
866,train_lr_0.1_n_200_d_4_s_30_leaf_16,435.75,434.96,439.27,433.18,438.49,436.33
858,train_lr_0.1_n_200_d_4_s_8_leaf_16,435.75,434.96,439.27,433.18,438.49,436.33
862,train_lr_0.1_n_200_d_4_s_16_leaf_16,435.75,434.96,439.27,433.18,438.49,436.33
982,train_lr_0.05_n_200_d_5_s_16_leaf_16,436.54,435.88,443.36,434.53,441.09,438.28
978,train_lr_0.05_n_200_d_5_s_8_leaf_16,436.54,435.88,443.36,434.53,441.09,438.28
986,train_lr_0.05_n_200_d_5_s_30_leaf_16,436.54,435.88,443.36,434.53,441.09,438.28
562,train_lr_0.1_n_200_d_4_s_6_leaf_10,433.57,431.79,436.68,430.26,436.34,433.73
574,train_lr_0.1_n_200_d_4_s_10_leaf_10,433.57,431.79,436.68,430.26,436.34,433.73
568,train_lr_0.1_n_200_d_4_s_8_leaf_10,433.57,431.79,436.68,430.26,436.34,433.73
572,train_lr_0.1_n_200_d_4_s_10_leaf_8,432.70,431.11,435.61,428.68,434.74,432.57
566,train_lr_0.1_n_200_d_4_s_8_leaf_8,432.70,431.11,435.61,428.68,434.74,432.57
560,train_lr_0.1_n_200_d_4_s_6_leaf_8,432.70,431.11,435.61,428.68,434.74,432.57
742,train_lr_0.05_n_200_d_5_s_6_leaf_10,434.24,433.95,440.72,432.11,437.85,435.77
748,train_lr_0.05_n_200_d_5_s_8_leaf_10,434.24,433.95,440.72,432.11,437.85,435.77
882,train_lr_0.1_n_500_d_3_s_8_leaf_16,435.41,433.38,438.77,430.93,437.06,435.11
886,train_lr_0.1_n_500_d_3_s_16_leaf_16,435.41,433.38,438.77,430.93,437.06,435.11
890,train_lr_0.1_n_500_d_3_s_30_leaf_16,435.41,433.38,438.77,430.93,437.06,435.11

#### gbr (lr_0.05_n_500_d_4_s_4_leaf_4) or (lr_0.05_n_200_d_5_s_2_leaf_4)

In [24]:
# xgb = pd.read_csv('xgb.csv', header = None)
# df = xgb

In [25]:
# xgb

In [26]:
# df[6] = np.round((df[1] + df[2] + df[3] + df[4] + df[5])/5, 2)

In [27]:
# df.to_csv('xgb.csv', header=False, index=False)