In [2]:
import pandas as pd

In [3]:
gbr = pd.read_csv('gbr.csv', header = None)
gbr.drop_duplicates(inplace=True)

In [4]:
gbr_val = gbr.iloc[1::2,:]
gbr_val

                        0       1       2       3       4       5       6
1    val_lr_0.1_n_100_d_3  638.83  662.74  588.76  555.95  522.82  593.82
3    val_lr_0.1_n_100_d_4  638.55  663.69  589.45  559.71  523.24  594.93
5    val_lr_0.1_n_100_d_5  637.49  663.34  596.80  563.95  527.71  597.86
7    val_lr_0.1_n_200_d_3  635.07  661.77  591.72  558.68  522.49  593.95
9    val_lr_0.1_n_200_d_4  636.18  665.38  600.08  565.96  529.37  599.39
11   val_lr_0.1_n_200_d_5  639.47  668.61  604.94  572.28  536.44  604.35
13   val_lr_0.1_n_400_d_3  631.41  665.06  599.46  562.87  527.68  597.30
15   val_lr_0.1_n_400_d_4  640.79  670.05  607.39  579.13  533.10  606.09
17   val_lr_0.1_n_400_d_5  645.21  677.13  623.10  592.47  548.15  617.21
19  val_lr_0.05_n_100_d_3  642.55  666.98  591.44  559.39  526.02  597.28
21  val_lr_0.05_n_100_d_4  640.79  665.19  588.47  558.59  524.34  595.48
23  val_lr_0.05_n_100_d_5  640.39  666.68  588.68  558.55  522.88  595.44
25  val_lr_0.05_n_200_d_3  635.79  663.04  589.22  556.27  523.75  593.61
27  val_lr_0.05_n_200_d_4  637.64  663.33  588.80  561.09  523.35  594.84
41   val_lr_0.2_n_100_d_3  636.21  662.55  596.95  561.80  524.02  596.31
43   val_lr_0.2_n_100_d_4  642.40  672.15  597.99  568.75  530.07  602.27
45   val_lr_0.2_n_100_d_5  640.83  671.77  614.58  582.16  539.23  609.71
47   val_lr_0.2_n_200_d_3  634.73  665.37  596.81  567.51  534.00  599.68
49   val_lr_0.2_n_200_d_4  644.79  680.78  612.62  579.29  536.70  610.84
51   val_lr_0.2_n_200_d_5  649.97  685.64  622.47  593.91  553.13  621.02
63  val_lr_0.05_n_200_d_5  638.66  665.71  592.29  563.59  524.65  596.98

In [5]:
gbr_val.sort_values(by=6, ascending=True)

                        0       1       2       3       4       5       6
25  val_lr_0.05_n_200_d_3  635.79  663.04  589.22  556.27  523.75  593.61
1    val_lr_0.1_n_100_d_3  638.83  662.74  588.76  555.95  522.82  593.82
7    val_lr_0.1_n_200_d_3  635.07  661.77  591.72  558.68  522.49  593.95
27  val_lr_0.05_n_200_d_4  637.64  663.33  588.80  561.09  523.35  594.84
3    val_lr_0.1_n_100_d_4  638.55  663.69  589.45  559.71  523.24  594.93
23  val_lr_0.05_n_100_d_5  640.39  666.68  588.68  558.55  522.88  595.44
21  val_lr_0.05_n_100_d_4  640.79  665.19  588.47  558.59  524.34  595.48
41   val_lr_0.2_n_100_d_3  636.21  662.55  596.95  561.80  524.02  596.31
63  val_lr_0.05_n_200_d_5  638.66  665.71  592.29  563.59  524.65  596.98
19  val_lr_0.05_n_100_d_3  642.55  666.98  591.44  559.39  526.02  597.28
13   val_lr_0.1_n_400_d_3  631.41  665.06  599.46  562.87  527.68  597.30
5    val_lr_0.1_n_100_d_5  637.49  663.34  596.80  563.95  527.71  597.86
9    val_lr_0.1_n_200_d_4  636.18  665.38  600.08  565.96  529.37  599.39
47   val_lr_0.2_n_200_d_3  634.73  665.37  596.81  567.51  534.00  599.68
43   val_lr_0.2_n_100_d_4  642.40  672.15  597.99  568.75  530.07  602.27
11   val_lr_0.1_n_200_d_5  639.47  668.61  604.94  572.28  536.44  604.35
15   val_lr_0.1_n_400_d_4  640.79  670.05  607.39  579.13  533.10  606.09
45   val_lr_0.2_n_100_d_5  640.83  671.77  614.58  582.16  539.23  609.71
49   val_lr_0.2_n_200_d_4  644.79  680.78  612.62  579.29  536.70  610.84
17   val_lr_0.1_n_400_d_5  645.21  677.13  623.10  592.47  548.15  617.21
51   val_lr_0.2_n_200_d_5  649.97  685.64  622.47  593.91  553.13  621.02

In [13]:
gbr.iloc[2], gbr.iloc[26],

(0    train_lr_0.1_n_100_d_4
 1                    544.71
 2                    539.03
 3                    552.52
 4                    559.04
 5                    570.02
 6                    553.06
 Name: 2, dtype: object,
 0    train_lr_0.05_n_200_d_4
 1                      545.3
 2                     537.99
 3                     557.84
 4                      560.1
 5                     568.47
 6                     553.94
 Name: 26, dtype: object)

### 약간 overfit이 좋음